/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLy;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import java.sql.*;
import java.util.ArrayList;
/**
 *
 * @author USER
 */
public class FormQuanLy extends javax.swing.JFrame {
    DefaultTableModel dtbBang;
    Connection conn;
    Statement pst = null;
    boolean end = false;
    boolean chonhe = false;
    boolean chonkhoi = false;
    boolean chonlop = false;
    
    /**
     * Creates new form FormQuanLy
     */
    public FormQuanLy() {
        initComponents();
        this.getContentPane().setSize(1100, 800);
        loadPage();


        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        pNutLenh = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        pTop = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pHeDaoTao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbHeDaoTao = new javax.swing.JComboBox<>();
        pLop = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbLop = new javax.swing.JComboBox<>();
        pKhoi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbKhoi = new javax.swing.JComboBox<>();
        pChiTietHocSinh = new javax.swing.JPanel();
        pMaHS = new javax.swing.JPanel();
        tfMaHS = new javax.swing.JLabel();
        jfMaHS = new javax.swing.JTextField();
        pTenHS = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jfHoten = new javax.swing.JTextField();
        pGt = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jfGioiTinh = new javax.swing.JTextField();
        pGVCN = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jfGVCN = new javax.swing.JTextField();
        pTenLop = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jfLop = new javax.swing.JTextField();
        pNgaysinh = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jfNgaySinh = new javax.swing.JTextField();
        pDiachi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDiaChi = new javax.swing.JTextArea();
        pNutChitiet = new javax.swing.JPanel();
        btDiem = new javax.swing.JButton();
        btChinhSua = new javax.swing.JButton();
        btThem = new javax.swing.JButton();
        Xóa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btLuu = new javax.swing.JButton();
        pBangHS = new javax.swing.JPanel();
        spBang = new javax.swing.JScrollPane();
        tbBang = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBox1.setText("jCheckBox1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton6.setText("Thêm Học Sinh");
        pNutLenh.add(jButton6);

        jButton7.setText("Xóa Học Sinh");
        pNutLenh.add(jButton7);

        jButton8.setText("Lưu");
        pNutLenh.add(jButton8);

        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });
        pNutLenh.add(btThoat);

        getContentPane().add(pNutLenh, java.awt.BorderLayout.PAGE_END);

        pTop.setPreferredSize(new java.awt.Dimension(700, 75));
        pTop.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("PHẦN MỀM QUẢN LÝ HỌC SINH  ");
        jPanel1.add(jLabel4);

        pTop.add(jPanel1, java.awt.BorderLayout.NORTH);

        pHeDaoTao.setPreferredSize(new java.awt.Dimension(233, 68));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Chọn Hệ Đào Tạo: ");
        pHeDaoTao.add(jLabel1);

        cbHeDaoTao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbHeDaoTaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbHeDaoTaoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbHeDaoTaoMousePressed(evt);
            }
        });
        cbHeDaoTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHeDaoTaoActionPerformed(evt);
            }
        });
        pHeDaoTao.add(cbHeDaoTao);

        pTop.add(pHeDaoTao, java.awt.BorderLayout.LINE_START);

        pLop.setPreferredSize(new java.awt.Dimension(233, 68));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Chọn Lớp: ");
        pLop.add(jLabel3);

        cbLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLopActionPerformed(evt);
            }
        });
        pLop.add(cbLop);

        pTop.add(pLop, java.awt.BorderLayout.LINE_END);

        pKhoi.setPreferredSize(new java.awt.Dimension(233, 68));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Chọn Khối: ");
        pKhoi.add(jLabel2);

        cbKhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKhoiActionPerformed(evt);
            }
        });
        pKhoi.add(cbKhoi);

        pTop.add(pKhoi, java.awt.BorderLayout.CENTER);

        getContentPane().add(pTop, java.awt.BorderLayout.NORTH);

        pChiTietHocSinh.setLayout(new java.awt.GridLayout(0, 1));

        tfMaHS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfMaHS.setText("Mã Học Sinh:");

        javax.swing.GroupLayout pMaHSLayout = new javax.swing.GroupLayout(pMaHS);
        pMaHS.setLayout(pMaHSLayout);
        pMaHSLayout.setHorizontalGroup(
            pMaHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMaHSLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tfMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jfMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pMaHSLayout.setVerticalGroup(
            pMaHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMaHSLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pMaHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pChiTietHocSinh.add(pMaHS);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Họ tên: ");

        javax.swing.GroupLayout pTenHSLayout = new javax.swing.GroupLayout(pTenHS);
        pTenHS.setLayout(pTenHSLayout);
        pTenHSLayout.setHorizontalGroup(
            pTenHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTenHSLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        pTenHSLayout.setVerticalGroup(
            pTenHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTenHSLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pTenHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pChiTietHocSinh.add(pTenHS);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Giới tính: ");

        javax.swing.GroupLayout pGtLayout = new javax.swing.GroupLayout(pGt);
        pGt.setLayout(pGtLayout);
        pGtLayout.setHorizontalGroup(
            pGtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGtLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jfGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        pGtLayout.setVerticalGroup(
            pGtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pChiTietHocSinh.add(pGt);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Giáo viên chủ nhiệm:");

        javax.swing.GroupLayout pGVCNLayout = new javax.swing.GroupLayout(pGVCN);
        pGVCN.setLayout(pGVCNLayout);
        pGVCNLayout.setHorizontalGroup(
            pGVCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGVCNLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jfGVCN, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        pGVCNLayout.setVerticalGroup(
            pGVCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGVCNLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pGVCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfGVCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pChiTietHocSinh.add(pGVCN);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Lớp:");

        javax.swing.GroupLayout pTenLopLayout = new javax.swing.GroupLayout(pTenLop);
        pTenLop.setLayout(pTenLopLayout);
        pTenLopLayout.setHorizontalGroup(
            pTenLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTenLopLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jfLop, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        pTenLopLayout.setVerticalGroup(
            pTenLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTenLopLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pTenLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pChiTietHocSinh.add(pTenLop);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Ngày sinh: ");

        javax.swing.GroupLayout pNgaysinhLayout = new javax.swing.GroupLayout(pNgaysinh);
        pNgaysinh.setLayout(pNgaysinhLayout);
        pNgaysinhLayout.setHorizontalGroup(
            pNgaysinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNgaysinhLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pNgaysinhLayout.setVerticalGroup(
            pNgaysinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNgaysinhLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pNgaysinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pChiTietHocSinh.add(pNgaysinh);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Địa chỉ: ");

        taDiaChi.setColumns(20);
        taDiaChi.setRows(5);
        jScrollPane1.setViewportView(taDiaChi);

        javax.swing.GroupLayout pDiachiLayout = new javax.swing.GroupLayout(pDiachi);
        pDiachi.setLayout(pDiachiLayout);
        pDiachiLayout.setHorizontalGroup(
            pDiachiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiachiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        pDiachiLayout.setVerticalGroup(
            pDiachiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiachiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDiachiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pDiachiLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pChiTietHocSinh.add(pDiachi);

        btDiem.setText("Xem điểm");
        pNutChitiet.add(btDiem);

        btChinhSua.setText("Chỉnh sửa");
        pNutChitiet.add(btChinhSua);

        btThem.setText("Thêm");
        pNutChitiet.add(btThem);

        Xóa.setText("Xóa");
        pNutChitiet.add(Xóa);

        btSua.setText("Sửa");
        pNutChitiet.add(btSua);

        btLuu.setText("Lưu");
        btLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuActionPerformed(evt);
            }
        });
        pNutChitiet.add(btLuu);

        pChiTietHocSinh.add(pNutChitiet);

        getContentPane().add(pChiTietHocSinh, java.awt.BorderLayout.EAST);

        spBang.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        spBang.setToolTipText("");
        spBang.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Học Sinh", "Tên Học Sinh", "Giới tính", "Ngày sinh"
            }
        ));
        spBang.setViewportView(tbBang);

        javax.swing.GroupLayout pBangHSLayout = new javax.swing.GroupLayout(pBangHS);
        pBangHS.setLayout(pBangHSLayout);
        pBangHSLayout.setHorizontalGroup(
            pBangHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spBang, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );
        pBangHSLayout.setVerticalGroup(
            pBangHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBangHSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spBang, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pBangHS, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLuuActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        if(btThoat.isSelected()){

            System.exit(0);
        }
    }//GEN-LAST:event_btThoatActionPerformed

    private void cbHeDaoTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHeDaoTaoActionPerformed
        if(cbKhoi.getItemCount()!=0){
            cbKhoi.removeAllItems();
        }
        if(cbHeDaoTao.getSelectedIndex() != -1){    
            String tenhe = cbHeDaoTao.getSelectedItem().toString();
            String sql = "select TENKHOI FROM KHOI, HEDAOTAO where KHOI.MAHE = HEDAOTAO.MAHE AND TENHE = '" + tenhe +"'";
            try {
                pst = conn.createStatement();
                ResultSet rskhoi;
                rskhoi = pst.executeQuery(sql); 
                while(rskhoi.next()){
                    cbKhoi.addItem(rskhoi.getString(1));
            }
            rskhoi.close();
            pst.cancel();
            } catch (SQLException ex) {
                Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbHeDaoTaoActionPerformed

    private void cbHeDaoTaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbHeDaoTaoMouseClicked
        
            
    }//GEN-LAST:event_cbHeDaoTaoMouseClicked

    private void cbHeDaoTaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbHeDaoTaoMousePressed
        
    }//GEN-LAST:event_cbHeDaoTaoMousePressed

    private void cbHeDaoTaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbHeDaoTaoMouseEntered
        
    }//GEN-LAST:event_cbHeDaoTaoMouseEntered

    private void cbKhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKhoiActionPerformed
        if(cbLop.getItemCount()!=0)
            cbLop.removeAllItems();
        if(cbKhoi.getSelectedIndex() != -1){
            String tenkhoi = cbKhoi.getSelectedItem().toString();
            String sql = "select TENLOP FROM LOP, KHOI where KHOI.MAKHOI = LOP.MAKHOI AND TENKHOI = N'" + tenkhoi +"'";
            try {
                pst = conn.createStatement();
                ResultSet rskhoi;
                rskhoi = pst.executeQuery(sql); 
                while(rskhoi.next()){
                    cbLop.addItem(rskhoi.getString(1));
            }
            rskhoi.close();
            pst.cancel();
            }catch (SQLException ex) {
                    Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbKhoiActionPerformed

    private void cbLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLopActionPerformed
//        if(tbBang.getRowCount()!=0)
//            tbBang.removeRowSelectionInterval(1, tbBang.getRowCount());
        if(cbLop.getSelectedIndex() != -1){
            String tenlop = cbLop.getSelectedItem().toString();
            String sql = "select MAHOCSINH, TENHOCSINH, GIOITINH, NGAYSINH from LOP, HOCSINH WHERE HOCSINH.MALOP = LOP.MALOP AND TENLOP = N'" + tenlop +"'";
            try {
                pst = conn.createStatement();
                ResultSet rshs;
                rshs = pst.executeQuery(sql); 
                DefaultTableModel ta = new DefaultTableModel();
                while(rshs.next()){
                    String t[] = {"","","",""};
                    ta.addRow(t);
            }
            rshs.close();
            pst.cancel();
            loadBang(ta);
            }catch (SQLException ex) {
                    Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_cbLopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLy().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Xóa;
    private javax.swing.JButton btChinhSua;
    private javax.swing.JButton btDiem;
    private javax.swing.JButton btLuu;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThoat;
    private javax.swing.JComboBox<String> cbHeDaoTao;
    private javax.swing.JComboBox<String> cbKhoi;
    private javax.swing.JComboBox<String> cbLop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jfGVCN;
    private javax.swing.JTextField jfGioiTinh;
    private javax.swing.JTextField jfHoten;
    private javax.swing.JTextField jfLop;
    private javax.swing.JTextField jfMaHS;
    private javax.swing.JTextField jfNgaySinh;
    private javax.swing.JPanel pBangHS;
    private javax.swing.JPanel pChiTietHocSinh;
    private javax.swing.JPanel pDiachi;
    private javax.swing.JPanel pGVCN;
    private javax.swing.JPanel pGt;
    private javax.swing.JPanel pHeDaoTao;
    private javax.swing.JPanel pKhoi;
    private javax.swing.JPanel pLop;
    private javax.swing.JPanel pMaHS;
    private javax.swing.JPanel pNgaysinh;
    private javax.swing.JPanel pNutChitiet;
    private javax.swing.JPanel pNutLenh;
    private javax.swing.JPanel pTenHS;
    private javax.swing.JPanel pTenLop;
    private javax.swing.JPanel pTop;
    private javax.swing.JScrollPane spBang;
    private javax.swing.JTextArea taDiaChi;
    private javax.swing.JTable tbBang;
    private javax.swing.JLabel tfMaHS;
    // End of variables declaration//GEN-END:variables

    private void loadBang(DefaultTableModel t) {
        String col[] = {"Mã Học Sinh", "Họ tên", "Giới tính", "Ngày sinh"};
        dtbBang = new DefaultTableModel();  
        dtbBang.addColumn(col);
        dtbBang.addRow(t.getDataVector());
        tbBang.setModel(dtbBang);
        spBang = new JScrollPane(tbBang);
        
    }

    private void loadPage(){
        
        String dbURL = "jdbc:sqlserver://Localhost;databaseName=QL_DSTRUONGHOC;user=sa;password=sa";
        try {
                conn = getConnection(dbURL);
                pst = conn.createStatement();
                String sql = "select TENHE from HEDAOTAO";
                ResultSet rt = pst.executeQuery(sql);
                while(rt.next()){
                    cbHeDaoTao.addItem(rt.getString(1));
                }
                rt.close();    
                pst.cancel();
        } catch (SQLException ex) {
            Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbHeDaoTao.setSelectedIndex(-1);
        cbKhoi.setSelectedIndex(-1);
        cbLop.setSelectedIndex(-1);
    }
    
    
    private boolean ktChonHe(boolean t){
        boolean kq = false;
        if(t == false){
            String tenhe = cbHeDaoTao.getSelectedItem().toString();
            String sql = "select TENKHOI FROM KHOI, HEDAOTAO where KHOI.MAHE = HEDAOTAO.MAHE AND TENHE = '" + tenhe +"'";
            ResultSet rskhoi;
            try {
                rskhoi = pst.executeQuery(sql); 
                while(rskhoi.next()){
                    cbKhoi.addItem(rskhoi.getString(1));
            }
            rskhoi.close();
            
            chonhe = true;
            }catch (SQLException ex) {
                Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return kq;
    }
    private boolean ktChonKhoi(boolean t){
        boolean kq = false;
        if(t == false){
            
        }
        return kq;
    }
    public static Connection getConnection(String dbURL) {
        Connection conn = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection(dbURL);
        } catch (Exception ex) {
            System.out.println("connect failure!");
            ex.printStackTrace();
        }
        return conn;
    }

}
