/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLy;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import java.sql.*;
import java.util.ArrayList;
/**
 *
 * @author USER
 */
public class FormQuanLy extends javax.swing.JFrame {
    ArrayList<HocSinh> dshs;
    DefaultTableModel dtbBang;
    Connection conn;
    Statement pst = null;
    PreparedStatement pre;
    String he;
    String ma;
    boolean showCT = true; 
    
    
    /**
     * Creates new form FormQuanLy
     */
    public FormQuanLy() {
        initComponents();
        dshs = new ArrayList<HocSinh>();
        this.setLocationRelativeTo(null);
        this.getContentPane().setSize(1100, 800);
        dtbBang = (DefaultTableModel)this.tbBang.getModel();
        loadPage();
        
    }
    public FormQuanLy(String t) {
        he = t;
        initComponents();
        this.getContentPane().setSize(1100, 800);
        dtbBang = (DefaultTableModel)this.tbBang.getModel();
        this.setLocationRelativeTo(null);
        loadPage();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlDiem = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jfHK1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jfHK2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btNhapDiem = new javax.swing.JButton();
        dlSearch = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jfSearchMa = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btTim = new javax.swing.JButton();
        dlXemDiem = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jfXemHK1 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jfXemHK2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jfDiemTK = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        btSuaDiem = new javax.swing.JButton();
        btLuuDiem = new javax.swing.JButton();
        pNutLenh = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btHuy = new javax.swing.JButton();
        btLuu = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        pTop = new javax.swing.JPanel();
        pTiTle = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btBack = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btSearch = new javax.swing.JButton();
        pChonKhoiLop = new javax.swing.JPanel();
        pKhoi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbKhoi = new javax.swing.JComboBox<>();
        pLop = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbLop = new javax.swing.JComboBox<>();
        pChiTietHocSinh = new javax.swing.JPanel();
        pMaHS = new javax.swing.JPanel();
        tfMaHS = new javax.swing.JLabel();
        jfMaHS = new javax.swing.JTextField();
        pTenHS = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jfHoten = new javax.swing.JTextField();
        pGt = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jfGioiTinh = new javax.swing.JTextField();
        pTenLop = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jfLop = new javax.swing.JTextField();
        pNgaysinh = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jfNgaySinh = new javax.swing.JTextField();
        pDiachi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDiaChi = new javax.swing.JTextArea();
        pNutChitiet = new javax.swing.JPanel();
        btDiem = new javax.swing.JButton();
        btThemDiem = new javax.swing.JButton();
        pBangHS = new javax.swing.JPanel();
        spBang = new javax.swing.JScrollPane();
        tbBang = new javax.swing.JTable();
        pGV = new javax.swing.JPanel();
        pSX = new javax.swing.JPanel();
        cbSapxep = new javax.swing.JComboBox<>();

        dlDiem.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                dlDiemWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dlDiemWindowClosing(evt);
            }
        });
        dlDiem.getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setText("Điểm HK1:");

        jfHK1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jfHK1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jfHK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        dlDiem.getContentPane().add(jPanel1);

        jLabel5.setText("Điểm HK2:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jfHK2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jfHK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        dlDiem.getContentPane().add(jPanel2);

        btNhapDiem.setText("Nhập điểm");
        btNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapDiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btNhapDiem)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btNhapDiem)
                .addContainerGap())
        );

        dlDiem.getContentPane().add(jPanel3);

        dlDiem.getAccessibleContext().setAccessibleParent(btThemDiem);

        dlSearch.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dlSearchWindowClosing(evt);
            }
        });
        dlSearch.getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jLabel11.setText("Nhập Mã học sinh ");
        jPanel4.add(jLabel11);

        jfSearchMa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jfSearchMa.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel4.add(jfSearchMa);

        dlSearch.getContentPane().add(jPanel4);

        btTim.setText("Tìm kiếm");
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });
        jPanel8.add(btTim);

        dlSearch.getContentPane().add(jPanel8);

        dlXemDiem.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                dlXemDiemWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dlXemDiemWindowClosing(evt);
            }
        });
        dlXemDiem.getContentPane().setLayout(new java.awt.GridLayout(4, 1));

        jLabel12.setText("Điểm HK1:");

        jfXemHK1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jfXemHK1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jfXemHK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        dlXemDiem.getContentPane().add(jPanel9);

        jLabel13.setText("Điểm HK2:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jfXemHK2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jfXemHK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        dlXemDiem.getContentPane().add(jPanel10);

        jLabel14.setText("Điểm Tổng kết:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfDiemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jfDiemTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        dlXemDiem.getContentPane().add(jPanel11);

        btSuaDiem.setText("Chỉnh sửa");
        btSuaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaDiemActionPerformed(evt);
            }
        });
        jPanel12.add(btSuaDiem);

        btLuuDiem.setText("Lưu");
        btLuuDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuDiemActionPerformed(evt);
            }
        });
        jPanel12.add(btLuuDiem);

        dlXemDiem.getContentPane().add(jPanel12);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pNutLenh.setBackground(new java.awt.Color(255, 0, 255));

        btThem.setText("Thêm Học Sinh");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        pNutLenh.add(btThem);

        btHuy.setText("Hủy");
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });
        pNutLenh.add(btHuy);

        btLuu.setText("Lưu");
        btLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuActionPerformed(evt);
            }
        });
        pNutLenh.add(btLuu);

        btXoa.setText("Xóa Học Sinh");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        pNutLenh.add(btXoa);

        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });
        pNutLenh.add(btThoat);

        getContentPane().add(pNutLenh, java.awt.BorderLayout.PAGE_END);

        pTop.setPreferredSize(new java.awt.Dimension(700, 75));
        pTop.setLayout(new java.awt.BorderLayout());

        pTiTle.setLayout(new java.awt.BorderLayout());

        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuanLyAnh/icon/backspace-arrow.png"))); // NOI18N
        btBack.setText("Back");
        btBack.setMaximumSize(new java.awt.Dimension(91, 39));
        btBack.setMinimumSize(new java.awt.Dimension(91, 37));
        btBack.setPreferredSize(new java.awt.Dimension(91, 32));
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        jPanel6.add(btBack);

        pTiTle.add(jPanel6, java.awt.BorderLayout.WEST);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("PHẦN MỀM QUẢN LÝ HỌC SINH  ");
        jPanel5.add(jLabel4);

        pTiTle.add(jPanel5, java.awt.BorderLayout.CENTER);

        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuanLyAnh/icon/magnifier-with-small-handle.png"))); // NOI18N
        btSearch.setText("Search");
        btSearch.setPreferredSize(new java.awt.Dimension(101, 32));
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        jPanel7.add(btSearch);

        pTiTle.add(jPanel7, java.awt.BorderLayout.EAST);

        pTop.add(pTiTle, java.awt.BorderLayout.NORTH);

        pChonKhoiLop.setLayout(new java.awt.GridLayout(1, 0));

        pKhoi.setPreferredSize(new java.awt.Dimension(233, 68));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Chọn Khối: ");
        pKhoi.add(jLabel2);

        cbKhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKhoiActionPerformed(evt);
            }
        });
        pKhoi.add(cbKhoi);

        pChonKhoiLop.add(pKhoi);

        pLop.setPreferredSize(new java.awt.Dimension(233, 68));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Chọn Lớp: ");
        pLop.add(jLabel3);

        cbLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLopActionPerformed(evt);
            }
        });
        pLop.add(cbLop);

        pChonKhoiLop.add(pLop);

        pTop.add(pChonKhoiLop, java.awt.BorderLayout.CENTER);

        getContentPane().add(pTop, java.awt.BorderLayout.NORTH);

        pChiTietHocSinh.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chi tiết"));
        pChiTietHocSinh.setForeground(new java.awt.Color(204, 255, 204));
        pChiTietHocSinh.setLayout(new java.awt.GridLayout(0, 1));

        tfMaHS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfMaHS.setText("Mã Học Sinh:");

        javax.swing.GroupLayout pMaHSLayout = new javax.swing.GroupLayout(pMaHS);
        pMaHS.setLayout(pMaHSLayout);
        pMaHSLayout.setHorizontalGroup(
            pMaHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMaHSLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tfMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jfMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pMaHSLayout.setVerticalGroup(
            pMaHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMaHSLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pMaHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pChiTietHocSinh.add(pMaHS);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Họ tên: ");

        javax.swing.GroupLayout pTenHSLayout = new javax.swing.GroupLayout(pTenHS);
        pTenHS.setLayout(pTenHSLayout);
        pTenHSLayout.setHorizontalGroup(
            pTenHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTenHSLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pTenHSLayout.setVerticalGroup(
            pTenHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTenHSLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(pTenHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pChiTietHocSinh.add(pTenHS);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Giới tính: ");

        javax.swing.GroupLayout pGtLayout = new javax.swing.GroupLayout(pGt);
        pGt.setLayout(pGtLayout);
        pGtLayout.setHorizontalGroup(
            pGtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGtLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jfGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pGtLayout.setVerticalGroup(
            pGtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGtLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pGtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pChiTietHocSinh.add(pGt);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Lớp:");

        javax.swing.GroupLayout pTenLopLayout = new javax.swing.GroupLayout(pTenLop);
        pTenLop.setLayout(pTenLopLayout);
        pTenLopLayout.setHorizontalGroup(
            pTenLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTenLopLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jfLop, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pTenLopLayout.setVerticalGroup(
            pTenLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTenLopLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pTenLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pChiTietHocSinh.add(pTenLop);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Ngày sinh: ");

        javax.swing.GroupLayout pNgaysinhLayout = new javax.swing.GroupLayout(pNgaysinh);
        pNgaysinh.setLayout(pNgaysinhLayout);
        pNgaysinhLayout.setHorizontalGroup(
            pNgaysinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNgaysinhLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pNgaysinhLayout.setVerticalGroup(
            pNgaysinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNgaysinhLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pNgaysinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pChiTietHocSinh.add(pNgaysinh);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Địa chỉ: ");

        taDiaChi.setColumns(20);
        taDiaChi.setRows(5);
        jScrollPane1.setViewportView(taDiaChi);

        javax.swing.GroupLayout pDiachiLayout = new javax.swing.GroupLayout(pDiachi);
        pDiachi.setLayout(pDiachiLayout);
        pDiachiLayout.setHorizontalGroup(
            pDiachiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiachiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pDiachiLayout.setVerticalGroup(
            pDiachiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDiachiLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pDiachiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pDiachiLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pChiTietHocSinh.add(pDiachi);

        btDiem.setText("Xem điểm");
        btDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDiemActionPerformed(evt);
            }
        });
        pNutChitiet.add(btDiem);

        btThemDiem.setText("Thêm điểm");
        btThemDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemDiemActionPerformed(evt);
            }
        });
        pNutChitiet.add(btThemDiem);

        pChiTietHocSinh.add(pNutChitiet);

        getContentPane().add(pChiTietHocSinh, java.awt.BorderLayout.EAST);

        pBangHS.setForeground(new java.awt.Color(255, 255, 51));
        pBangHS.setLayout(new java.awt.BorderLayout());

        spBang.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        spBang.setToolTipText("");
        spBang.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spBang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Học Sinh", "Tên Học Sinh", "Giới tính", "Ngày sinh", "Điểm TK"
            }
        ));
        tbBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBangMouseClicked(evt);
            }
        });
        spBang.setViewportView(tbBang);

        pBangHS.add(spBang, java.awt.BorderLayout.CENTER);

        pGV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pGV.setLayout(new java.awt.BorderLayout());

        pSX.setLayout(new java.awt.BorderLayout());

        cbSapxep.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbSapxep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-Z", "Học lực tăng dần", "Học lực giảm dần" }));
        cbSapxep.setToolTipText("");
        cbSapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSapxepActionPerformed(evt);
            }
        });
        pSX.add(cbSapxep, java.awt.BorderLayout.CENTER);

        pGV.add(pSX, java.awt.BorderLayout.EAST);

        pBangHS.add(pGV, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pBangHS, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        if(btThoat.isSelected()){
            System.exit(0);
        }
    }//GEN-LAST:event_btThoatActionPerformed

    private void cbKhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKhoiActionPerformed
        if(cbLop.getItemCount()!=0){
            cbLop.removeAllItems();
            btThemDiem.setVisible(false);
        }
        
        if(cbKhoi.getSelectedIndex() != -1){
            String tenkhoi = cbKhoi.getSelectedItem().toString();
            String sql = "select TENLOP FROM LOP, KHOI where KHOI.MAKHOI = LOP.MAKHOI AND TENKHOI = N'" + tenkhoi +"'";
            try {
                pre = conn.prepareStatement(sql);
                ResultSet rskhoi;
                rskhoi = pre.executeQuery(); 
                while(rskhoi.next()){
                    cbLop.addItem(rskhoi.getString(1));
            }
            rskhoi.close();
            pre.cancel();
            }catch (SQLException ex) {
                    Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            btThemDiem.setVisible(false);
            pBangHS.setVisible(false);
            pChiTietHocSinh.setVisible(false);
        }
        cleanCT();
        cbLop.setSelectedIndex(-1);
    }//GEN-LAST:event_cbKhoiActionPerformed

    private void cbLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLopActionPerformed
        dtbBang.setRowCount(0);
        if(cbLop.getSelectedIndex() != -1){
            String tenlop = cbLop.getSelectedItem().toString();
            String malop = "select MALOP from LOP where TENLOP= N'" + tenlop + "'";
            try {
                pre = conn.prepareStatement(malop);
                ResultSet rshs;
                rshs = pre.executeQuery();
                while (rshs.next())
                    ma = rshs.getString(1);
                String sql = "select MAHOCSINH, TENHOCSINH, GIOITINH, NGAYSINH, DIEMTK  from LOP, HOCSINH ";
                sql+= " FULL OUTER JOIN KETQUA ON HOCSINH.MAHOCSINH = KETQUA.MAHS\n" + " WHERE TENLOP = '"+ tenlop +"' AND HOCSINH.MALOP = LOP.MALOP";
                pre = conn.prepareStatement(sql);
                rshs = pre.executeQuery();
                while(rshs.next()){
                    Vector<String> ta = new Vector<String>();
                    ta.add(rshs.getString(1));
                    ta.add(rshs.getString(2));
                    ta.add(rshs.getString(3));
                    ta.add(rshs.getString(4));
                    ta.add(rshs.getString(5));
                    dtbBang.addRow(ta);
            }
            rshs.close();
            pre.cancel();
            
            }catch (SQLException ex) {
                    Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        cleanCT();
        pBangHS.setVisible(true);
        
    }//GEN-LAST:event_cbLopActionPerformed

    private void tbBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBangMouseClicked
        String mahs;
        if(tbBang.getSelectedRow()== -1)
            return;
        mahs = (String) dtbBang.getValueAt(tbBang.getSelectedRow(), 0);
        jfMaHS.setText(mahs);
        jfHoten.setText((String) dtbBang.getValueAt(tbBang.getSelectedRow(), 1));
        jfGioiTinh.setText((String) dtbBang.getValueAt(tbBang.getSelectedRow(), 2));
        jfNgaySinh.setText((String) dtbBang.getValueAt(tbBang.getSelectedRow(), 3));
        jfLop.setText(cbLop.getSelectedItem().toString());
        String sql = "select DIACHI from HOCSINH WHERE MAHOCSINH = N'" + mahs +"'";
            try {
                pre = conn.prepareStatement(sql);
                ResultSet rshs;
                rshs = pre.executeQuery();     
                while(rshs.next()){
                    taDiaChi.setText(rshs.getString(1));
                sql = "select DIEMHK1, DIEMHK2, DIEMTK FROM KETQUA WHERE MAHS = '" + jfMaHS.getText() +"'";
                pre = conn.prepareStatement(sql);
                ResultSet rs = pre.executeQuery();
                while(rs.next()){
                    jfXemHK1.setText(rs.getString(1));
                    jfXemHK2.setText(rs.getString(2));
                    jfDiemTK.setText(rs.getString(3));
                }   
            }
            rshs.close();
            pre.cancel();
            }catch (SQLException ex) {
                    Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
        pChiTietHocSinh.setVisible(true);
        btDiem.setVisible(true);
        btThemDiem.setVisible(false);
    }//GEN-LAST:event_tbBangMouseClicked

    private void cbSapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSapxepActionPerformed
        dtbBang.setRowCount(0);
        dshs = new ArrayList<HocSinh>();
        dshs.removeAll(dshs);
        if(cbSapxep.getSelectedIndex()!=-1){
            String tenlop = cbLop.getSelectedItem().toString();
            String sql = " SET QUOTED_IDENTIFIER OFF\n SET ANSI_NULLS ON \n" +
            " select MAHOCSINH, TENHOCSINH, GIOITINH, NGAYSINH, DIEMTK from LOP, HOCSINH, KETQUA";
            if(cbSapxep.getSelectedIndex()==0)
                sql +=   " WHERE HOCSINH.MALOP = LOP.MALOP AND TENLOP = N'" + tenlop +"'" + " and KETQUA.MAHS = MAHOCSINH ORDER BY TENHOCSINH ASC";
            else if(cbSapxep.getSelectedIndex()==1){
                sql += " WHERE HOCSINH.MALOP = LOP.MALOP AND TENLOP = N'" + tenlop +"'" + " and KETQUA.MAHS = MAHOCSINH ORDER BY DIEMTK DESC ";
            }
            else if(cbSapxep.getSelectedIndex()==2){
                sql+= " WHERE HOCSINH.MALOP = LOP.MALOP AND TENLOP = N'" + tenlop +"'" + " and KETQUA.MAHS = MAHOCSINH ORDER BY DIEMTK ASC ";
            }
            try {
                pre = conn.prepareStatement(sql);
                ResultSet rshs;
                rshs = pre.executeQuery();    
                while(rshs.next()){
                    Vector<String> ta = new Vector<String>();
                    ta.add(rshs.getString(1));
                    ta.add(rshs.getString(2));
                    ta.add(rshs.getString(3));
                    ta.add(rshs.getString(4));
                    ta.add(""+rshs.getFloat(5));
                    HocSinh hs = new HocSinh(ta.elementAt(0),ta.elementAt(1),ta.elementAt(2),ta.elementAt(3));
                    
                    dshs.add(hs);
                    dtbBang.addRow(ta);
            }
            rshs.close();
            pre.cancel();
            
            }catch (SQLException ex) {
                    Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
    }//GEN-LAST:event_cbSapxepActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        dlSearch.show();
        dlSearch.setSize(400, 200);
        dlSearch.setLocationRelativeTo(null);
        this.setEnabled(false);
    }//GEN-LAST:event_btSearchActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        TrangChu ct = new TrangChu();
        ct.show();
        this.hide();
    }//GEN-LAST:event_btBackActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        cleanCT();
        btThemDiem.setVisible(true);
        btDiem.setVisible(false);
        btThoat.setVisible(false);
        btXoa.setVisible(false);
    }//GEN-LAST:event_btThemActionPerformed

    private void btLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuActionPerformed
        if(CheckMa(jfMaHS.getText())){
            int i = JOptionPane.showConfirmDialog(null, "Trùng mã học sinh", "Thong bao", JOptionPane.YES_NO_CANCEL_OPTION);
            if(i == JOptionPane.YES_OPTION){
                String up = "UPDATE HOCSINH SET TENHOCSINH = ? , MALOP = ?, NGAYSINH = ?, DIACHI = ?, GIOITINH = ? ";
                up += "where MAHOCSINH = '" + jfMaHS.getText() +"'";
                try {
                    pre = conn.prepareStatement(up);
                    pre.setString(1, jfHoten.getText());
                    pre.setString(2, ma);
                    pre.setString(3, jfNgaySinh.getText());
                    pre.setString(4, taDiaChi.getText());
                    pre.setString(5, jfGioiTinh.getText());
                    int a = pre.executeUpdate();
                    if(a==1){
                        JOptionPane.showConfirmDialog(null, "Cập nhật thanh cong", "Thong bao", JOptionPane.OK_OPTION);
                    }
                    else
                        JOptionPane.showConfirmDialog(null, "Cập nhật that bai", "Thong bao", JOptionPane.OK_OPTION);
                } catch (SQLException ex) {
                    Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else    
                return;
        }
        else{          
            try {
                String sql = "Insert into HocSinh (MAHOCSINH ,TENHOCSINH, MALOP, NGAYSINH, DIACHI, GIOITINH) values (?,?,?,?,?,?)";
                pre = conn.prepareStatement(sql);
                pre.setString(1, jfMaHS.getText());
                pre.setString(2, jfHoten.getText());
                pre.setString(3, ma);
                pre.setString(4, jfNgaySinh.getText());
                pre.setString(5, taDiaChi.getText());
                pre.setString(6, jfGioiTinh.getText());
                pre.executeUpdate();
                String kq = "Insert into KetQua (MaHS, MALOP , DiemHK1, DiemHK2) values (?,?,?,?)";
                pre = conn.prepareStatement(kq);
                pre.setString(1, jfMaHS.getText());
                pre.setString(2, ma);
                pre.setString(3, jfHK1.getText());
                pre.setString(4, jfHK2.getText());
                int i = pre.executeUpdate();
                if(i==1){
                    JOptionPane.showConfirmDialog(null, "Them thanh cong", "Thong bao", JOptionPane.OK_OPTION);
                }
                else
                    JOptionPane.showConfirmDialog(null, "Them that bai", "Thong bao", JOptionPane.OK_OPTION);

            } catch (SQLException ex) {
                Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        loadBang(cbLop.getSelectedItem().toString());
        btThemDiem.setVisible(false);
        btDiem.setVisible(true);
        cleanCT();
    }//GEN-LAST:event_btLuuActionPerformed

    private void btThemDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemDiemActionPerformed
        dlDiem.show();
        this.setEnabled(false);
    }//GEN-LAST:event_btThemDiemActionPerformed

    private void dlDiemWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlDiemWindowClosing
        this.setEnabled(true);
        dlDiem.hide();
    }//GEN-LAST:event_dlDiemWindowClosing

    private void dlDiemWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlDiemWindowActivated
        dlDiem.setLocationRelativeTo(null);
        dlDiem.setSize(400,200);
    }//GEN-LAST:event_dlDiemWindowActivated

    private void btNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapDiemActionPerformed
        this.setEnabled(true);
        dlDiem.hide();
    }//GEN-LAST:event_btNhapDiemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        String kq = "DELETE KETQUA WHERE MAHS = '" + jfMaHS.getText() + "'";
        String sql = "DELETE HOCSINH WHERE MAHOCSINH = '" + jfMaHS.getText() + "'";
        try {
            pre = conn.prepareStatement(kq);
            pre.executeUpdate();
            pre = conn.prepareStatement(sql);
            int i = pre.executeUpdate();
            if(i == 1){
                JOptionPane.showConfirmDialog(null, "Xóa thanh cong", "Thong bao", JOptionPane.OK_OPTION);
            }
            else
                JOptionPane.showConfirmDialog(null, "Xóa thất bại", "Thong bao", JOptionPane.OK_OPTION);
        } catch (SQLException ex) {
            Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadBang(cbLop.getSelectedItem().toString());
        cleanCT();
    }//GEN-LAST:event_btXoaActionPerformed

    private void dlSearchWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlSearchWindowClosing
        dlDiem.hide();
        this.setEnabled(true);
    }//GEN-LAST:event_dlSearchWindowClosing

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
        String sql = "select MAHOCSINH, TENHOCSINH, GIOITINH, TENLOP , NGAYSINH, DIACHI, DIEMHK1, DIEMHK2, DIEMTK  from HOCSINH, KETQUA, LOP ";
        sql += "WHERE MAHOCSINH = MAHS AND HOCSINH.MALOP = LOP.MALOP AND MAHOCSINH = '" + jfSearchMa.getText() +"'";
        try {
            pre = conn.prepareStatement(sql);
            ResultSet rs = pre.executeQuery();
            while(rs.next()){
                jfMaHS.setText(rs.getString(1));
                jfHoten.setText(rs.getString(2));
                jfGioiTinh.setText(rs.getString(3));
                jfLop.setText(rs.getString(4));
                jfNgaySinh.setText(rs.getString(5));
                taDiaChi.setText(rs.getString(6));
                jfXemHK1.setText(rs.getString(7));
                jfXemHK2.setText(rs.getString(8));
                jfDiemTK.setText(rs.getString(9));
            }
            pre.cancel();
            dlSearch.hide();
            this.setEnabled(true);
            pBangHS.setVisible(false);
            pChiTietHocSinh.setVisible(true);
            this.requestFocus();
            cbKhoi.setSelectedIndex(-1);
            cbLop.setSelectedIndex(-1);
        } catch (SQLException ex) {
            Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btTimActionPerformed

    private void btSuaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaDiemActionPerformed
        jfXemHK1.setText("");
        jfXemHK2.setText("");
        jfXemHK1.requestFocus();
    }//GEN-LAST:event_btSuaDiemActionPerformed

    private void dlXemDiemWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlXemDiemWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_dlXemDiemWindowActivated

    private void dlXemDiemWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlXemDiemWindowClosing
        dlXemDiem.hide();
        this.setEnabled(true);
        this.jfMaHS.requestFocus();
    }//GEN-LAST:event_dlXemDiemWindowClosing

    private void btDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDiemActionPerformed
        dlXemDiem.show();
        dlXemDiem.setSize(400,200);
        dlXemDiem.setLocationRelativeTo(null);
        this.setEnabled(false);
        String sql = "select DIEMHK1, DIEMHK2, DIEMTK FROM KETQUA WHERE MAHS = '" + jfMaHS.getText() +"'";
        try {
            pre = conn.prepareStatement(sql);
            ResultSet rs = pre.executeQuery();
            while(rs.next()){
                jfXemHK1.setText(rs.getString(1));
                jfXemHK2.setText(rs.getString(2));
                jfDiemTK.setText(rs.getString(3));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btDiemActionPerformed

    private void btLuuDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuDiemActionPerformed
        String sql = "UPDATE KETQUA SET DIEMHK1 = " + jfXemHK1.getText() + ", DIEMHK2 = " + jfXemHK2.getText();
        sql += " WHERE MAHS = '" + jfMaHS.getText() + "'";
        try {
            pre = conn.prepareStatement(sql);
            int i = pre.executeUpdate();
            if(i == 1){
                JOptionPane.showConfirmDialog(null, "Chỉnh sửa điểm thành công", "Thong bao", JOptionPane.OK_OPTION);
                dlXemDiem.hide();
                this.setEnabled(true);
                this.requestFocus();
            }
            else
                JOptionPane.showConfirmDialog(null, "Chỉnh sửa điểm thất bại", "Thong bao", JOptionPane.OK_OPTION);
        } catch (SQLException ex) {
            Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }  
        loadBang(cbLop.getSelectedItem().toString());
    }//GEN-LAST:event_btLuuDiemActionPerformed

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        btDiem.setVisible(true);
        btThemDiem.setVisible(true);
        btThoat.setVisible(true);
        btXoa.setVisible(true);
        this.requestFocus();
    }//GEN-LAST:event_btHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btDiem;
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btLuu;
    private javax.swing.JButton btLuuDiem;
    private javax.swing.JButton btNhapDiem;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btSuaDiem;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThemDiem;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btTim;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbKhoi;
    private javax.swing.JComboBox<String> cbLop;
    private javax.swing.JComboBox<String> cbSapxep;
    private javax.swing.JDialog dlDiem;
    private javax.swing.JDialog dlSearch;
    private javax.swing.JDialog dlXemDiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jfDiemTK;
    private javax.swing.JTextField jfGioiTinh;
    private javax.swing.JTextField jfHK1;
    private javax.swing.JTextField jfHK2;
    private javax.swing.JTextField jfHoten;
    private javax.swing.JTextField jfLop;
    private javax.swing.JTextField jfMaHS;
    private javax.swing.JTextField jfNgaySinh;
    private javax.swing.JTextField jfSearchMa;
    private javax.swing.JTextField jfXemHK1;
    private javax.swing.JTextField jfXemHK2;
    private javax.swing.JPanel pBangHS;
    private javax.swing.JPanel pChiTietHocSinh;
    private javax.swing.JPanel pChonKhoiLop;
    private javax.swing.JPanel pDiachi;
    private javax.swing.JPanel pGV;
    private javax.swing.JPanel pGt;
    private javax.swing.JPanel pKhoi;
    private javax.swing.JPanel pLop;
    private javax.swing.JPanel pMaHS;
    private javax.swing.JPanel pNgaysinh;
    private javax.swing.JPanel pNutChitiet;
    private javax.swing.JPanel pNutLenh;
    private javax.swing.JPanel pSX;
    private javax.swing.JPanel pTenHS;
    private javax.swing.JPanel pTenLop;
    private javax.swing.JPanel pTiTle;
    private javax.swing.JPanel pTop;
    private javax.swing.JScrollPane spBang;
    private javax.swing.JTextArea taDiaChi;
    private javax.swing.JTable tbBang;
    private javax.swing.JLabel tfMaHS;
    // End of variables declaration//GEN-END:variables

    private void loadPage(){
        String dbURL = "jdbc:sqlserver://Localhost;databaseName=QL_DSTRUONGHOC;user=sa;password=sa";
        try {
                conn = getConnection(dbURL);
                String sql = "select TENKHOI FROM KHOI, HEDAOTAO where KHOI.MAHE = HEDAOTAO.MAHE AND TENHE = N'" + he +"'";
                pre = conn.prepareStatement(sql);   
                ResultSet rt = pre.executeQuery();
                while(rt.next()){
                    cbKhoi.addItem(rt.getString(1));
                }
                rt.close();    
                pre.cancel();
        } catch (SQLException ex) {
            Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbKhoi.setSelectedIndex(-1);
        cbLop.setSelectedIndex(-1);
        
        
        cleanCT();
    }
    
    
    
    
    public static Connection getConnection(String dbURL) {
        Connection conn = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection(dbURL);
        } catch (Exception ex) {
            System.out.println("connect failure!");
            ex.printStackTrace();
        }
        return conn;
    }
    private void cleanCT(){
        jfMaHS.setText("");
        taDiaChi.setText("");
        jfHoten.setText("");
        jfGioiTinh.setText("");
        jfLop.setText("");
        jfNgaySinh.setText("");
        jfXemHK1.setText("");
        jfXemHK2.setText("");
        jfDiemTK.setText("");
        jfHK1.setText("");
        jfHK2.setText("");
        jfMaHS.requestFocus();
   }

    private void loadBang(String tenlop){
        dtbBang.setRowCount(0);
        String malop = "select MALOP from LOP where TENLOP= N'" + tenlop + "'";
            try {
                pst = conn.createStatement();
                ResultSet rshs;
                rshs = pst.executeQuery(malop);
                while (rshs.next())
                    ma = rshs.getString(1);
                String sql = "select MAHOCSINH, TENHOCSINH, GIOITINH, NGAYSINH, DIEMTK  from LOP, HOCSINH ";
                sql+= " FULL OUTER JOIN KETQUA ON HOCSINH.MAHOCSINH = KETQUA.MAHS\n" + " WHERE TENLOP = '"+ tenlop +"' AND HOCSINH.MALOP = LOP.MALOP";
                pre = conn.prepareStatement(sql);
                rshs = pre.executeQuery();
                while(rshs.next()){
                    Vector<String> ta = new Vector<String>();
                    ta.add(rshs.getString(1));
                    ta.add(rshs.getString(2));
                    ta.add(rshs.getString(3));
                    ta.add(rshs.getString(4));
                    ta.add(rshs.getString(5));
                    dtbBang.addRow(ta);
            }
            rshs.close();
            pre.cancel();
            
            }catch (SQLException ex) {
                    Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    private boolean CheckMa(String mahs){
        boolean kq = false;
        String sql = "select MAHOCSINH FROM HOCSINH WHERE MAHOCSINH = '" + mahs + "'";
        try {
            pre = conn.prepareStatement(sql);
            ResultSet rs = pre.executeQuery();
            while(rs.next()){
                kq = true;
            }     
        } catch (SQLException ex) {
            Logger.getLogger(FormQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
        return kq;
    }
}
